Feat/exception handling
microsoftgraph/msgraph-cli-archived pull request #10
Opened 2020-08-24 07:53 UTC by jobala

## Overview
This PR adds exception handlers for 403 and ClientAuthenticationErrors.

## Screenshots
![image](https://user-images.githubusercontent.com/12011447/91017219-96075580-e5f6-11ea-9e09-fe1b8782898b.png)

![image](https://user-images.githubusercontent.com/12011447/91018031-b2f05880-e5f7-11ea-8122-9487e5d8d798.png)

2020-08-25 05:31 UTC, MIchaelMainer requested changes
We should define a set of custom CLIError objects to represent the different types of errors that may be raised by this CLI.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/custom_browser_credential.py
> +            token = self._app.acquire_token_silent(scopes,
`token` can have the value of `None` per https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/646cd6045d79cba7554d79070bce3ac2db3941b6/msal/application.py#L503. Line 33 should account for that and call `login()` since the refresh token isn't available. No use in making the user issue `mg login` again.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/custom_browser_credential.py
> +            raise CLIError('Login to run this command')
We should just call `login` and get the access token at this point instead of `raise CLIError`. I mentioned this last time that it is the pattern, here is more guidance on the matter: https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/646cd6045d79cba7554d79070bce3ac2db3941b6/msal/application.py#L406.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/custom_browser_credential.py
> +        super().__init__(**kwargs)
Why are we updating this class when we are going to use the beta InteractiveBrowserCredential?

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +                    self.handle_403()
We are losing a lot of potential useful information by swallowing the response headers and body. We should maintain all of the response information in a standard [OData error object](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358908) for errors returned by the server.   

We also need to be very careful about handling service errors in special ways where we map error to custom client behaviors. We want to default to being a pass through of errors for most scenarios. There are just too many potential service error scenarios for us to support with mapped special behaviors. 

This comment also applies to line 234.

Since `GraphCliCommandInvoker.execute()` already does an arg check for `--debug` and `--verbose`, I suggest that error messages suggest the use of those flags to get more information, and if those flags are provided, and the error is a service error, we should dump the OData response object in JSON form to the command line.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +        raise CLIError(
Comment is global to the entire project.

CLIError is intended to be a base class for exceptions that occur when using the CLI. We should define derived classes for the following scenarios:

`class ServiceError(CLIError)` - Used to pass through errors that are returned in a response from the service.
`class ClientError(CLIError)` - Represent errors originating from the msgraph-sdk-python-core library.
`class MSGraphCLIError(CLIError)` - Errors that are raised in the MSGraph CLI layer.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +        raise CLIError(ex.message)
Comment is global to the entire project.

I'm not finding a global final capture of Exception. How are we capturing Exception and communicating to the CLI in a unified way? 

Nevermind, I see it in `execute()`.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +from azure.core.exceptions import HttpResponseError, ClientAuthenticationError
Comment is applicable to **invocation.py**

Comment the classes and methods in this file with helpful comments for your reviewers and future maintainers.
Add copyright header.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/__init__.py
> +from ._exception_handler import auth_exception_handler
Document these classes and methods.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/_exception_handler.py
> +def auth_exception_handler(exception):
File named with a leading underscore, but this definition doesn't contain a leading underscore. Is this supposed to be `_auth_exception_handler(exception)`? Also, might as well make the file name and the handler match unless you plan on adding more auth exception handlers.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/_exception_handler.py
> +    raise CLIError(exception)
We should raise a more specific exception than `CLIError`.

2020-08-25 05:31 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/custom.py
> +    result = credential.login(login_scopes)
I suspect that credential.login can return a non-null `result` that does not have a valid access token.  I just can't find where `_get_token_by_auth_code` is defined to verify. Can you provide a link to its definition?

2020-08-25 16:05 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +        raise CLIError(
We should have a design discussion around how our client libraries handle exceptions and capture that information here: https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/content/ErrorContent.md

2020-08-26 05:55 UTC, jobala commented on msgraph/cli/command_modules/authentication/custom.py
> +    result = credential.login(login_scopes)
Yes, it returns a non null result when the login is successful. We are getting it from the superclass `InteractiveBrowserCredential`

2020-08-26 05:59 UTC, jobala commented on msgraph/cli/command_modules/authentication/_exception_handler.py
> +def auth_exception_handler(exception):
Prefixing an identifier with an underscore in Python implies that the identifier is private. Also, in Python files are modules. The underscore here implies that the `_exception_handler` module is private within the authentication package. Prefixing an underscore on the `auth_exception_handler` method will mean that it is private within the `_exception_handler` module but we are using the method in another module.

2020-08-26 06:01 UTC, jobala commented on msgraph/cli/core/custom_browser_credential.py
> +        super().__init__(**kwargs)
The change is idempotent, it just uses python3 syntax for initializing the parent.

2020-08-26 06:03 UTC, jobala commented on msgraph/cli/core/custom_browser_credential.py
> +            raise CLIError('Login to run this command')
We talked about this in person, commenting for the sake of other reviewers.

We don't know what scopes the user needs to fulfil the command. So even if we log them in they will have to login again with the correct scopes to run the command successfully.

2020-08-26 06:04 UTC, jobala commented on msgraph/cli/core/custom_browser_credential.py
> +            token = self._app.acquire_token_silent(scopes,
We talked about this in person, commenting for the sake of other reviewers.

We don't know what scopes the user needs to fulfil the command. So even if we log them in they will have to login again with the correct scopes to run the command successfully.

2020-08-27 15:23 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/custom.py
> +    result = credential.login(login_scopes)
Exception is raised if no access token

2020-08-27 15:26 UTC, MIchaelMainer commented on msgraph/cli/core/custom_browser_credential.py
> +            token = self._app.acquire_token_silent(scopes,
Agreed.

2020-08-27 15:26 UTC, MIchaelMainer commented on msgraph/cli/core/custom_browser_credential.py
> +            raise CLIError('Login to run this command')
Agreed

2020-08-27 16:02 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +        raise CLIError(
Tracked with https://github.com/microsoftgraph/msgraph-sdk-design/issues/35

2020-08-27 16:04 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/_exception_handler.py
> +    raise CLIError(exception)
Tracked

2020-08-27 16:05 UTC, MIchaelMainer commented on msgraph/cli/core/invocation.py
> +                    self.handle_403()
This will be covered in the service exception class.

2020-08-27 16:05 UTC, MIchaelMainer approved these changes

2020-08-27 18:00 UTC, merged