Add extension command module
microsoftgraph/msgraph-cli-archived pull request #153
Opened 2021-06-24 12:06 UTC by calebkiage

## Overview

Adds a command to manage 3rd party extensions in the cli

### Demo

```
(msgraph-cli) > ./mg extension list
[]

(msgraph-cli) >./mg extension show
ERROR: the following arguments are required: --name/-n

TRY THIS:
az extension show --name MyExtension
Show an extension. (autogenerated)

az extension list
List the installed extensions. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/extension#az_extension_show
Read more about the command in reference docs

(msgraph-cli) >./mg extension list-available
[
  {
    "experimental": false,
    "installed": false,
    "name": "mail_beta",
    "preview": true,
    "summary": "Microsoft Azure Command-Line Tools Mail Extension",
    "version": "0.1.0"
  }
]

```

## Testing Instructions

* Run the command `./mg extension --help` to see the available commands
* Run any of the commands to test.

2021-06-24 12:41 UTC, samwelkanda requested changes

2021-06-24 12:41 UTC, samwelkanda commented on msgraph/cli/command_modules/extension/_help.py
> +    long-summary: Default path is azure-cli-extensions folder under the CLI running python environment lib path, configurable by environment variable AZURE_EXTENSION_SYS_DIR. On Windows, you may need
We need to replace `azure` references with `msgraph` in the help strings

2021-06-24 12:41 UTC, samwelkanda commented on msgraph/cli/command_modules/extension/_help.py
> +    text: az extension add --name anextension
Also replace `az` with `mg` in the samples.

2021-06-24 13:01 UTC, calebkiage commented on msgraph/cli/command_modules/extension/_help.py
> +    long-summary: Default path is azure-cli-extensions folder under the CLI running python environment lib path, configurable by environment variable AZURE_EXTENSION_SYS_DIR. On Windows, you may need
I haven't yet updated the extensions folder.

2021-06-24 13:28 UTC, samwelkanda commented on msgraph/cli/command_modules/extension/_help.py
> +    long-summary: Default path is azure-cli-extensions folder under the CLI running python environment lib path, configurable by environment variable AZURE_EXTENSION_SYS_DIR. On Windows, you may need
Cool let's leave it as is until we update that.

2021-06-24 13:38 UTC, samwelkanda approved these changes

2021-06-24 22:37 UTC, MIchaelMainer requested changes
I think we should clarify that these are CLI extensions. For example, in Microsoft Graph, there are schema extensions and open extensions. This could cause confusion by generically calling this extensions.

I propose something like:

```
./mg cli-extension list-available
./mg cli-extensions list-available
./mg cliextension list-available
```

I think the first option is best.

2021-06-28 06:30 UTC, jobala commented
@MIchaelMainer I prefer `./mg extension` because it provides an interface similar to Azure CLI's and most of our users will be familiar with how Azure CLI works. I would tradeoff the confusion with consistency with Azure CLI.

2021-06-28 22:32 UTC, MIchaelMainer commented
In terms of consistency, with the same concept in Azure, yes, keeping the name would provide consistency in the CLI experience. If we changed the name, it would still be functionally consistent, but without the same command group name as experienced in the Azure CLI. We also have to consider the term **extension** across of Microsoft Graph:

https://docs.microsoft.com/en-us/search/?scope=graph&view=graph-rest-1.0&terms=extension

There are a lot of hits on extension.

We need to think about a future where we generate CLI code snippets and inject into the documentation. We also need to consider the impact on search indices when customers search on the term extension. Extension is already an overloaded term in Microsoft Graph (and software development in general). By not disambiguating it here, we increase the potential for confusion across the CLI, documentation, and pretty much anywhere else that Microsoft Graph based content is indexed or used.

Case in point: if the folks who created the schema extension feature called it extension, we would have had to disambiguate the term at this point. But they did the right thing and disambiguated the term so that we can have this discussion 😄.   There is little ambiguity by calling it cli-extension.

2021-06-30 23:05 UTC, MIchaelMainer approved these changes

2021-07-06 19:31 UTC, MIchaelMainer commented on Pipfile
> +allow_prereleases = true
I'm curious why we want to support pre-releases.

2021-07-06 19:31 UTC, MIchaelMainer commented on build_scripts/automation/build_package.py
> +    # check_call(['python', 'setup.py', "sdist", "--format", "zip", '-d', dest], cwd=absdirpath)
nit: cleanup commented code.

2021-07-06 19:31 UTC, MIchaelMainer commented on build_scripts/automation/upload_extensions.py
> +        _upload_wheel(ext_info=ext_info, updated_indexes=updated_indexes, ext_file=ext_file, ext_name=ext_name, client=client)
Are there any cases where _upload_wheel could fail in middle of this loop resulting in updated wheels without an update to the index?

2021-07-07 13:57 UTC, calebkiage commented on Pipfile
> +allow_prereleases = true
I had to enable this to successfully run `pipenv install`

2021-07-07 14:10 UTC, calebkiage commented on build_scripts/automation/upload_extensions.py
> +        _upload_wheel(ext_info=ext_info, updated_indexes=updated_indexes, ext_file=ext_file, ext_name=ext_name, client=client)
That's a good question. Currently, this script only handles the first time run at the moment and running it a second time will overwrite the uploaded extensions. I want to update it to enable updating existing indexes on the next phase of the task. That update should handle for failures too.

2021-07-08 11:16 UTC, jobala approved these changes

2021-07-08 12:06 UTC, samwelkanda approved these changes

2021-07-08 15:06 UTC, merged