Task/update identity
microsoftgraph/msgraph-cli-archived pull request #16
Opened 2020-09-14 08:27 UTC by jobala

## Overview
This PR uses `azure-identity==1.4.0b7` which is a beta release. We are using a beta release so that we can give feedback -- if any -- to the azure-identity team.  I have also encapsulated the authentication logic which was spread between `custom.py` and `custom_browser_credential.py` in an `authentication` object.

Fixes #9

2020-09-15 04:13 UTC, ddyett commented
do we have a timeline for azure identity to come out of beta?

2020-09-15 04:25 UTC, ddyett commented on msgraph/cli/core/authentication.py
> +        auth_record = self.get_credential(login=True).authenticate(scopes=scopes)
what data is this auth_record, a token?

2020-09-15 04:31 UTC, MIchaelMainer commented
@ddyett The feature we need, InteractiveBrowserCredential with persistent token cache, will come out of beta in November. 

https://github.com/Azure/azure-sdk-for-python/issues/13189#issuecomment-677796303

2020-09-15 04:40 UTC, ddyett commented
> @ddyett The feature we need, InteractiveBrowserCredential with persistent token cache, will come out of beta in November.
> 
> [Azure/azure-sdk-for-python#13189 (comment)](https://github.com/Azure/azure-sdk-for-python/issues/13189#issuecomment-677796303)

ah ok makes sense

2020-09-15 05:12 UTC, jobala commented on msgraph/cli/core/authentication.py
> +        auth_record = self.get_credential(login=True).authenticate(scopes=scopes)
**auth_record** is an object containing the following properties;
1. authority
2. client_id
3. home_account_id
4. tenant_id
5. username

The credential object uses this object to know which user is signed in.

2020-09-15 17:45 UTC, ddyett approved these changes

2020-09-16 01:16 UTC, MIchaelMainer requested changes

2020-09-16 01:16 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +            file.write(record)
We should handle IOError in case `AUTH_RECORD_LOCATION` is not accessible with the current user context. I suggest a message to indicate that the user can still use the CLI, they will have to login again.

2020-09-16 01:16 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +            remove(AUTH_RECORD_LOCATION)
Handle IOError in the case the file is locked or some other file access issue occurs. I think we should print the error message and state that the user wasn't logged out

2020-09-16 17:33 UTC, MIchaelMainer approved these changes

2020-09-16 17:57 UTC, merged