Feat/show warning message
microsoftgraph/msgraph-cli-archived pull request #39
Opened 2020-10-26 08:58 UTC by jobala

## Overview

Lets the user know when the **access-token** is **stored**  in **plain text**
### Demo

![image](https://user-images.githubusercontent.com/12011447/97152546-1fb3da80-1782-11eb-8f7c-e7aae5959092.png)

### Notes

N/A

## Testing Instructions

* Pull these changes
* Run `./graph login --scopes user.read ` in  **wsl** or **Ubuntu**
* Observe the warning message

Fixes #24

2020-10-27 00:23 UTC, MIchaelMainer requested changes

2020-10-27 00:23 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +            print('Token stored in a plain text file, install PyGObject to encrypt token')
Since this is a security scenario, we should give the user the option to install PyGObject now before taking the next step. We want to encourage the secure path. Ideally, after their approval, we run it. Otherwise, give the likely install command for PyGObject.

2020-10-27 00:23 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +    def get_credential(self, auth_record=None, unencrypt_cache=False) -> InteractiveBrowserCredential:
Document the condition for the expected exception when libsecret is not present, since we are relying on that behavior and it won't be apparent that it will be thrown.

2020-10-27 07:09 UTC, jobala commented on msgraph/cli/core/authentication.py
> +            print('Token stored in a plain text file, install PyGObject to encrypt token')
@MIchaelMainer what do you think of logging in the user only when we can store the access token securely?

The flow will be :
1. User log in
2. Oops, we can't store the token securely. Install PyGObject then log in.
3. Here are the instructions for installing PyGObject
4. User logs in successfully.

2020-10-27 07:21 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +            print('Token stored in a plain text file, install PyGObject to encrypt token')
Yes, that will work well. We just don't want to block them to run this. If there are scenarios where they may not be able to install PyGObject, we should still give them a chance to run this in unsafe mode, but it should be an explicit understood choice for the user. Otherwise, if we are confident that they can always install PyGObject, then let's make this the only path. 

If we link out to any instructions, we should make it an aka.ms link.

2020-10-28 08:21 UTC, jobala commented on msgraph/cli/core/authentication.py
> +            print('Token stored in a plain text file, install PyGObject to encrypt token')
Users can always install PyGObject.

2020-10-28 16:56 UTC, MIchaelMainer requested changes

2020-10-28 16:56 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +        except:
You should handle the specific known exception that is thrown when PyObject is not installed. All other exceptions should not be handled here as they are not expected.

2020-10-28 16:56 UTC, MIchaelMainer commented on msgraph/cli/core/authentication.py
> +    def get_credential(self, auth_record=None) -> InteractiveBrowserCredential:
Exceptions that we expect should be documented on the method where they can occur. 

https://realpython.com/documenting-python-code/

2020-10-30 08:57 UTC, MIchaelMainer approved these changes

2020-10-30 12:54 UTC, merged