Feat/national clouds
microsoftgraph/msgraph-cli-archived pull request #52
Opened 2020-11-21 19:45 UTC by jobala

## Overview

Adds commands to list and add clouds and modifies the login command to accept a client-id

### Demo

**Selecting a cloud**
![image](https://user-images.githubusercontent.com/12011447/99886076-b755fd00-2c4a-11eb-95a4-50d1d82b9332.png)

### Notes
N/A

## Testing Instructions

* Pull this PR
* Run `./mg cloud select` to select a cloud
* Run `./mg cloud add --name <name> --endpoint <endpoint> --authority<authority> to add a new cloud`

2020-11-23 17:56 UTC, ddyett commented
how does a user check which cloud they are pointed to.  Don't think I see a command for that?

2020-11-23 17:58 UTC, ddyett commented
I think powershell has the ability to provide custom paths as well.  see https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/425

2020-11-23 18:06 UTC, ddyett commented on msgraph/cli/core/commands/client_factory.py
> +        base_url = 'https://graph.microsoft.com/v1.0'
probably define as a default in constants file.

2020-11-23 18:25 UTC, ddyett commented
can you attach a sample of what the profile.json looks like.  makes it easier to follow

2020-11-24 14:50 UTC, MIchaelMainer commented on msgraph/cli/core/constants.py
> +DEFAULT_CLIENT_ID = '837b13ab-6d14-4dc7-837f-8954cc87fdc0'
Is this an official client_id?

2020-11-24 14:50 UTC, MIchaelMainer commented on msgraph/cli/core/installed_extensions.py
> +installed_extensions = [
I think we can ignore this file as it is created when we run install_extensions.py.

2020-11-24 14:50 UTC, MIchaelMainer commented on msgraph/command_modules/profile/__init__.py
> +            group.command('add', 'add_cloud')
Missing the `current` command

2020-11-24 14:50 UTC, MIchaelMainer commented on msgraph/command_modules/profile/__init__.py
> +            group.command('add', 'add_cloud')
I really like the `add` for the future proofing. We should have a delete command to balance this. The delete should only affect user defined endpoints

2020-11-24 14:50 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_help.py
> +from knack.help_files import helps
Can we have the help file contents defined in the same place as the commands they describe? Or is this the way?

2020-11-24 14:56 UTC, MIchaelMainer commented on msgraph/command_modules/profile/custom.py
> +        user_defined_clouds.append(cloud)
Before we append, we should make sure that the endpoint doesn't already exist.

2020-11-24 14:59 UTC, MIchaelMainer commented on msgraph/command_modules/profile/custom.py
> +    supported_clouds = list(DEFAULT_CLOUDS.keys())
I suggest that we list not just the friendly name, but also the endpoint and authority so that customers can see what exactly is supported

2020-11-24 15:10 UTC, jobala commented on msgraph/command_modules/profile/_help.py
> +from knack.help_files import helps
We borrowed this convention from azure-cli

2020-11-24 15:42 UTC, MIchaelMainer commented on msgraph/cli/core/installed_extensions.py
> +installed_extensions = [
TIL: We need this for packaging.

2020-11-24 15:48 UTC, MIchaelMainer commented on msgraph/command_modules/profile/custom.py
> +        user_defined_clouds.append(cloud)
If we support delete, we don't need to worry about this - customer can delete their dups.

2020-11-24 16:02 UTC, jobala commented on msgraph/cli/core/constants.py
> +DEFAULT_CLIENT_ID = '837b13ab-6d14-4dc7-837f-8954cc87fdc0'
Nope.

2020-11-24 17:15 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_help.py
> +from knack.help_files import helps
Let's make sure that there is clear comment with a link to where the custom command knack help is located.

2020-11-24 19:03 UTC, peombwa commented on msgraph/command_modules/profile/__init__.py
> +            group.command('add', 'add_cloud')
We should also add `mg cloud set` for modifying user defined clouds.

2020-11-24 19:03 UTC, peombwa commented on msgraph/cli/core/constants.py
> +        'endpoint': 'https://graph.microsoft.com/v1.0',
Consider renaming this to something like `GraphEndpoint` since `endpoint` is too general. The same applies to `mg cloud *` parameters.

2020-11-24 19:03 UTC, peombwa commented on msgraph/cli/core/constants.py
> +        'authority': 'https://login.microsoftonline.com'
Authority is not be the right name for this property since it generally refers to an `Identity provider instance + SignIn audience/Tenant` e.g. `https://login.microsoftonline.com/<tenant>/`. See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#authority.

Consider renaming this to something like `AzureADEndpoint`. The same applies to `mg cloud *` parameters.

2020-11-24 19:25 UTC, peombwa commented on msgraph/cli/core/authentication.py
> +    def login(self, scopes: [str], client_id=None) -> bool:
Consider adding `tenant_id` to support multi-tenant scenarios.

2020-11-24 19:36 UTC, peombwa commented on msgraph/cli/core/constants.py
> +        'endpoint': 'https://graph.microsoft.de/v1.0',
From the `Sample profile.json` in the PR overview, should the `endpoint` be the base url minus the service version or with the service version? 

Ideally, you would want the national cloud Graph endpoint to be service version agnostic. This will make it easy to support both `beta` and `v1.0` down the line.

2020-11-25 06:20 UTC, jobala commented on msgraph/command_modules/profile/__init__.py
> +            group.command('add', 'add_cloud')
I prefer `mg cloud update` to `mg cloud set`.

2020-11-25 06:31 UTC, jobala commented on msgraph/cli/core/constants.py
> +        'endpoint': 'https://graph.microsoft.com/v1.0',
Not sure what you mean by

> The same applies to mg cloud * parameters.

2020-11-25 06:37 UTC, jobala commented on msgraph/cli/core/constants.py
> +        'endpoint': 'https://graph.microsoft.de/v1.0',
I am aware of the limitation that comes with adding the service version to the base_url. I will decouple the version from the base_url in #33

2020-12-02 18:11 UTC, MIchaelMainer requested changes

2020-12-02 18:11 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_cloud_manager.py
> +class CloudManager:
I think this class is internal. If so, name should be `_CloudManager`.

Also, add class comments about why we need this class. Not everyone that works on this will know about the existence of different clouds. Provide a link to https://docs.microsoft.com/en-us/graph/deployments

2020-12-02 18:11 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_cloud_manager.py
> +            if name not in cloud.keys():
This doesn't appear to delete a user defined cloud entry. I think it should be something like:

```python
if name in cloud.keys():
    cloud.pop(name)
    result.append(cloud)
```

We should also return information that indicates whether the entry was deleted or not.

2020-12-02 18:11 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_cloud_manager.py
> +            if name not in cloud.keys():
Also, what happens if the deleted cloud is the current cloud? If the user defined cloud is the current cloud, then we should should delete the current cloud entry so the default one is used.

2020-12-02 18:11 UTC, MIchaelMainer commented on msgraph/command_modules/profile/custom.py
> +    print(f'Cloud "{name}" deleted successfully')
We don't have confirmation that the delete was a success. [delete_cloud()](https://github.com/microsoftgraph/msgraph-cli/pull/52/files/276d34e8f32f867e0cbbf20ed4ccea9352d3184c..875770ac7a862081ad12bd492a859b510cff71e9#diff-2d9117d6f1651117603755b24c6d8ea80ab8ad0755fd2ee589cfdc4e27a39302R66) should return a value that tells us the results of the delete operation.

2020-12-02 18:11 UTC, MIchaelMainer commented on msgraph/command_modules/profile/custom.py
> +    print(f'Cloud "{name}" added successfully')
`create_cloud()` should return status about whether the cloud was added successfully. Use the status as input to `print`.

2020-12-02 20:07 UTC, jobala commented on msgraph/command_modules/profile/_cloud_manager.py
> +class CloudManager:
The cloud manager class is not internal to the `_cloud_manager.py` **module** it is consumed in the `custom.py` **module.**

2020-12-02 21:21 UTC, jobala commented on msgraph/command_modules/profile/custom.py
> +    print(f'Cloud "{name}" added successfully')
@MIchaelMainer and I had a conversation about this and we decided to throw an error instead of returning a status. This will involve parameterizing write_profile so that we can pass custom error messages to it.

2020-12-02 21:21 UTC, jobala commented on msgraph/command_modules/profile/custom.py
> +    print(f'Cloud "{name}" deleted successfully')
@MIchaelMainer and I had a conversation about this and we decided to throw an error instead of returning a status. This will involve parameterizing write_profile so that we can pass custom error messages to it.

2020-12-02 21:23 UTC, jobala commented on msgraph/command_modules/profile/_cloud_manager.py
> +            if name not in cloud.keys():
@MIchaelMainer  and I talked about this and we decided to throw an error when user tries to delete a cloud that is also a current cloud. Users will only be able to delete a cloud that is not current.

2020-12-02 21:55 UTC, jobala commented on msgraph/command_modules/profile/_cloud_manager.py
> +            if name not in cloud.keys():
@MIchaelMainer 

This deletes a cloud by first loading all user defined clouds to memory, filtering out the cloud to delete and then saving the filtered list of clouds. We are not using `cloud.pop(name)` because `profile['user_defined_clouds']` returns a list and not a dictionary so we can't pop by name.

2020-12-02 22:11 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_cloud_manager.py
> +        # throw an error if the cloud does not exit
nit: exist

2020-12-02 22:13 UTC, MIchaelMainer approved these changes

2020-12-02 22:13 UTC, MIchaelMainer commented on msgraph/command_modules/profile/_cloud_manager.py
> +            raise CLIError(f'The cloud "{name}" could not be deleted because it is a current cloud')
Give instructions to change the current cloud with the command to change it.

2020-12-02 22:27 UTC, MIchaelMainer approved these changes

2020-12-02 22:37 UTC, merged