Move cloud commands to profile command group
microsoftgraph/msgraph-cli-archived pull request #55
Opened 2020-12-10 11:46 UTC by jobala

## Overview

Move commands from the **cloud** command group to the **profile** command group.
Removes show-current commands from the cloud and graph-version command groups
Adds `show-profile` command

### Demo

![image](https://user-images.githubusercontent.com/12011447/101768116-3d50bf80-3af6-11eb-8370-0dce01fba106.png)

### Notes

N/A

## Testing Instructions

* Pull these changes
* Build and run the docker container -- instructions are in README.md
* Run `mg profile -h` to see the list of commands
* Run `mg profile show-profile` to see your current profile

2020-12-17 17:22 UTC, MIchaelMainer requested changes
Using `mg profile` results in 

```cli
usage: mg profile [-h]
                  {select-cloud,add-cloud,update-cloud,delete-cloud,select-version,show-profile}
                  ...
mg profile: error: the following arguments are required: _subcommand
```
Let's remove that `...` and provide a user friendly message with specific instructions. Something like:

`The mg profile command must be used with a subcommand. Run mg profile -h for information on available subcommands.`

2020-12-17 17:22 UTC, MIchaelMainer commented on msgraph/cli/__main__.py
> +    if not has_profile:
For the user experience, as part of the first run experience when a profile is first created, I think it would be helpful to tell the customer that:
1) we've created a profile with the specified user setting values.
2) that they can make change to the profile. They should `Learn more by running mg profile -h`.

2021-01-04 07:37 UTC, jobala commented
@MIchaelMainer I assume your comment below, is to help users get unstack when they run a wrong command.

> Let's remove that ... and provide a user friendly message with specific instructions. Something like:

Where does the usage instructions fall short? It shows the commands available under profile command group.

> usage: mg profile [-h]
                  {select-cloud,add-cloud,update-cloud,delete-cloud,select-version,show-profile

2021-01-05 07:59 UTC, MIchaelMainer commented
The usage instructions part is good. I think we can make a friendlier, more helpful message than `mg profile: error: the following arguments are required: _subcommand`. I believe that a CLI experience should be somewhat conversational (I think I picked this up from the CLI guidance doc). That's why I proposed: `The mg profile command must be used with a subcommand. Run mg profile -h for information on available subcommands.`

2021-01-05 13:52 UTC, jobala commented
Makes sense. The change won't be trivial so I have created #57 to track your suggestion.

2021-01-05 17:35 UTC, MIchaelMainer approved these changes

2021-01-05 17:35 UTC, MIchaelMainer commented on msgraph/cli/__main__.py
> +def show_profile_msg():
nit: this should probably be `show_default_profile_msg()`

2021-01-05 20:28 UTC, merged