Feat/login
microsoftgraph/msgraph-cli-archived pull request #8
Opened 2020-08-13 17:13 UTC by jobala

## Overview
Adds login command

## Screenshots
![image](https://user-images.githubusercontent.com/12011447/90307348-da4f7300-dedd-11ea-8c29-d1d797a9f445.png)

![image](https://user-images.githubusercontent.com/12011447/90307357-ffdc7c80-dedd-11ea-87f5-179a9b81ed28.png)

## Notes
The login functionality does **not use** device code flow, because we want to provide a similar user experience to azure-cli which has an interactive browser experience. To achieve the interactivity we extend the functionality provided by `InteractiveBrowserCredential` from `azure.identity`. Acquired tokens are persisted securely by msal-extensions.

2020-08-13 18:38 UTC, MIchaelMainer requested changes
This is an exciting PR. It is helpful to capture screenshots in the PR since changes like this that have a UI experience.

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/custom.py
> +    login_scopes = scopes.split(',')
We should trim the scopes in case the user specifies the scopes with a space: `user.read, message.read`

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/__init__.py
> +from msgraph.cli.core import AzCommandsLoader
Global: Add copyright headers to all files. Add documentation to your code files. You can't assume the code reviewers or future maintainers will understand the context of these files. It puts additional cognitive load on the reviewers which will distract from the review. This is especially true for our team since we don't typically have a team of people working in an SDK, it is usually one person with reviewers who are not intimately familiar with the code base (or language for that matter). It is better to error on the side of over documenting your code than to under document (we can use IDEs to collapse distracting comments). 

Let the code tell us *how* it is done, and the comments tell us *why* it is done. And because of the nature of our team, I tend to think that we should comment more than usual on the *what* is being done.

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/custom.py
> +from msgraph.cli.core.msal import CustomBrowserCredential
Since we are defining **login** in this file, I think it would make more sense to name this file login.py.

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/_help.py
> +short-summary: Log in to Microsoft Graph
I think we assume that the user's tenant has user consent enabled or that the user is an admin. Otherwise, a tenant admin will need to consent to the CLI app for the tenant. I suggest that we make this clear in a `long-summary` element.

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/custom.py
> +    result = credential.get_token(*login_scopes)
There are a couple of errors that can be returned by `get_token`. We should handle them, especially since users are responsible for typing in scope strings, and print the messages to the console so that hopefully, the messages are useful and the customer can fix the issue themselves. 

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.4.0/azure.identity.html#azure.identity.InteractiveBrowserCredential

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/core/msal.py
> +class CustomBrowserCredential(InteractiveBrowserCredential):
File name is `msal.py`, class name is `CustomBrowserCredential`. Change the file name to match the class name. It will help code searches.

2020-08-13 18:38 UTC, MIchaelMainer commented on msgraph/cli/core/msal.py
> +from azure.identity import InteractiveBrowserCredential
Taking a step back, is there a reason why we don't just add this improvement to InteractiveBrowserCredential in azure.identity? This would accrue value to many other projects, not just ours.

2020-08-13 18:48 UTC, MIchaelMainer commented on msgraph/cli/core/msal.py
> +            token = app.acquire_token_silent(scopes, account=accounts[0], **kwargs)
If `acquire_token_silent` can't find a token, is an error returned? I think we should kick off `get_access` token if the token is expired or if an error is returned.

2020-08-14 06:41 UTC, jobala commented on msgraph/cli/core/msal.py
> +            token = app.acquire_token_silent(scopes, account=accounts[0], **kwargs)
Interesting question. In principle acquire_token_silent will always return a token unless the user is not signed in. If a token is expired it will make a refresh token call and get a new token.

2020-08-14 14:01 UTC, jobala commented on msgraph/cli/command_modules/authentication/custom.py
> +    login_scopes = scopes.split(',')
A user can only pass a list of scopes without spaces by design.

2020-08-14 14:05 UTC, jobala commented on msgraph/cli/command_modules/authentication/__init__.py
> +from msgraph.cli.core import AzCommandsLoader
I agree with your sentiment that we should comment code. I am pushing back on having to comment all the code so as to provide context to reviewers. There's a risk of re-documenting the framework code. I try to be pragmatic about comments and avoid  adding comments to framework code since that information already exists on the framework's documentation. 

It's better to have that discussion or seek clarification on Github threads rather than on the code.

2020-08-14 14:07 UTC, jobala commented on msgraph/cli/command_modules/authentication/custom.py
> +from msgraph.cli.core.msal import CustomBrowserCredential
This file will contain multiple authentication functions like logout, get_new_token etc, logging in is just one of them.

2020-08-14 14:09 UTC, jobala commented on msgraph/cli/command_modules/authentication/_help.py
> +short-summary: Log in to Microsoft Graph
msgraph-cli currently doesn't support user provided tenants. Is this something we should add?

2020-08-14 14:13 UTC, jobala commented on msgraph/cli/command_modules/authentication/custom.py
> +    result = credential.get_token(*login_scopes)
Tracked in [#5224](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/5224)

2020-08-14 14:25 UTC, jobala commented on msgraph/cli/core/msal.py
> +            token = app.acquire_token_silent(scopes, account=accounts[0], **kwargs)
From docs

> Acquire an access token for given account, without user interaction.

        It is done either by finding a valid access token from cache,
        or by finding a valid refresh token from cache and then automatically
        use it to redeem a new access token

2020-08-14 17:08 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/custom.py
> +    login_scopes = scopes.split(',')
How do you enforce that the users can only pass a list of comma separated values without spaces? I'm not seeing where this is enforced.

2020-08-14 17:19 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/__init__.py
> +from msgraph.cli.core import AzCommandsLoader
I'm very confused. You state that you agree with the sentiment about commenting code, and then go on to state that you won't add comments. This is not just context for code reviewers. This is also for future maintainers. While you and I are available for discussions at this moment, you will not be available for discussions with future maintainers, unless you are committing to that ;-).

I also don't understand your statement about re-documenting framework code. You aren't writing framework code, but are writing code that interacts with a framework/library.

2020-08-14 17:24 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/_help.py
> +short-summary: Log in to Microsoft Graph
If I understand you correctly, I'm not saying a user should be able to bring their own clientId that they registered in their own Azure app registration. 

I'm concerned for the case where user consent is disabled for a Azure AD tenant. How will the user experience play out if user consent is disabled? https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent#:~:text=To%20configure%20user%20consent%20settings%20through%20the%20Azure,setting%20you%27d%20like%20to%20configure%20for%20all%20users.

2020-08-14 17:28 UTC, MIchaelMainer commented on msgraph/cli/core/msal.py
> +            token = app.acquire_token_silent(scopes, account=accounts[0], **kwargs)
But what if the cache is removed or otherwise inaccessible? The pattern I've seen in other languages is that if acquire_token_silent fails for any reason, we restart the acquire token interactively flow.

2020-08-14 19:24 UTC, jobala commented on msgraph/cli/command_modules/authentication/__init__.py
> +from msgraph.cli.core import AzCommandsLoader
I see your point, hadn't thought of future maintainers.  Code that interacts with a framework is framework code.

2020-08-15 06:58 UTC, jobala commented on msgraph/cli/command_modules/authentication/custom.py
> +    login_scopes = scopes.split(',')
What I meant is that the CLI framework will throw an error when a user runs the command `mg login user.read, user.read.all` because it will read the second scope as a different argument. 

![image](https://user-images.githubusercontent.com/12011447/90307299-657c3900-dedd-11ea-936f-bf1970b75ba8.png)

I have added an example that users will see when they run `mg login -h`
![image](https://user-images.githubusercontent.com/12011447/90307339-b4c26980-dedd-11ea-9539-d5047dee8436.png)

msgraph-cli is now also striping whitespaces.

2020-08-17 07:52 UTC, jobala commented on msgraph/cli/command_modules/authentication/_help.py
> +short-summary: Log in to Microsoft Graph
@MIchaelMainer I can simulate this scenario using my work account and requesting for a permission that requires admin consent ie `user.read.all`. If user consent is disabled, the user can either sign in with an admin profile or return to the application without granting consent. 

![image](https://user-images.githubusercontent.com/12011447/90371403-92645380-e077-11ea-9c6d-f408f9865f04.png)

Returning to the application without granting consent results in a login failure.

2020-08-17 11:14 UTC, jobala commented on msgraph/cli/core/msal.py
> +            token = app.acquire_token_silent(scopes, account=accounts[0], **kwargs)
@MIchaelMainer  I don't think that's the right approach for our use case.

1. We don't know what scopes are required for the command the user is running.
2. The scenario you described `But what if the cache is removed or otherwise inaccessible` is synonimous to the logged out state. We should ask the user to log in. This is the behavior in Azure CLI as well.

2020-08-18 15:24 UTC, MIchaelMainer commented on msgraph/cli/core/msal.py
> +            token = app.acquire_token_silent(scopes, account=accounts[0], **kwargs)
Tracked with [5753](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_boards/board/t/Graph%20Developer%20Experiences%20Team/Stories/?workitem=5753)

2020-08-18 15:39 UTC, MIchaelMainer commented on msgraph/cli/core/msal.py
> +from azure.identity import InteractiveBrowserCredential
Tracked with https://github.com/microsoftgraph/msgraph-cli/issues/9

2020-08-18 16:10 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/_help.py
> +short-summary: Log in to Microsoft Graph
I think this experience is good enough for now. I still want to see more explanation in a `long-summary` that states something like: "Logs in a user to Microsoft Graph with the specified scopes. You must specify the scopes before you use commands. You will need to log out and log back in to consent to additional scopes."

From the login example, you should remove the admin only `user.read.all` so that regular users are less likely to hit the admin consent dialog.

2020-08-18 17:11 UTC, MIchaelMainer commented on msgraph/cli/command_modules/authentication/__init__.py
> +from msgraph.cli.core import AzCommandsLoader
We clarified in conversation our mutual misunderstanding. Unresolving so we can address adding copyright headers and comments to all files that need them.

2020-08-20 17:52 UTC, MIchaelMainer approved these changes
No need to add missing comments to CustomInteractiveBrowserCredential as ideally we get the persistent x-platform support in azure.identity.

2020-08-20 17:54 UTC, merged