Task/telemetry headers
microsoftgraph/msgraph-cli-archived pull request #97
Opened 2021-04-26 09:05 UTC by jobala

## Overview

Adds a telemetry header by adding a `UserAgent` header with the value `msgraph-cli-version`

### Demo

<img width="1285" alt="Screen Shot 2021-04-26 at 12 02 38 PM" src="https://user-images.githubusercontent.com/12011447/116057345-6332c700-a687-11eb-97db-c24a9cc3fb49.png">

### Notes

## Testing Instructions

N/A

Closes #83

2021-04-29 06:22 UTC, MIchaelMainer requested changes

2021-04-29 06:22 UTC, MIchaelMainer commented on msgraph/cli/core/commands/client_factory.py
> +        user_agent_policy=UserAgentPolicy(base_user_agent=f'msgraph-cli-{__version__}'))
We should use the SdkVersion header for the CLI. [Python core will support appending CLI version header](https://github.com/microsoftgraph/msgraph-sdk-python-core/pull/74/files#diff-2673bd0d8a598e3dc640277b3e7128f7413ceb03f72a7b9c9c84bf5e07ebc6d1R37). This way we have a clean pairing between CLI version and Python Core in the same header. We run reports based on SdkVersion header.

> The SdkVersion version can contain multiple values, or appear multiple times in a request. Values should be comma delimited as normal header lists are if the SdkVersion contains multiple values. e.g.

Note that I think the example in this section of the TelemetryHandler spec is not ideal with the MyApp example. The customer should use User-Agent for that.

Ref: https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/TelemetryHandler.md

2021-04-30 10:32 UTC, jobala commented on msgraph/cli/core/commands/client_factory.py
> +        user_agent_policy=UserAgentPolicy(base_user_agent=f'msgraph-cli-{__version__}'))
@MIchaelMainer why should we use the SdkVersion header? How difficult is it to run reports off a different header property?

I considered using the SdkVersion header but decided to use the User-Agent header because the CLI is a client/application and not a library.

2021-05-02 04:42 UTC, samwelkanda commented on msgraph/cli/core/commands/client_factory.py
> +        user_agent_policy=UserAgentPolicy(base_user_agent=f'msgraph-cli-{__version__}'))
@MIchaelMainer just wondering, we might be moving to the azure core at some point, do we still expect to make use of the python core within the CLI?

2021-05-10 15:34 UTC, jobala commented on msgraph/cli/core/commands/client_factory.py
> +        user_agent_policy=UserAgentPolicy(base_user_agent=f'msgraph-cli-{__version__}'))
@MIchaelMainer I have updated this to use SdkVersion

2021-05-10 15:37 UTC, MIchaelMainer approved these changes

2021-05-10 15:38 UTC, merged